[workspace]
resolver = "3"
members = ["crates/*/*"]

[workspace.dependencies]
imap-tls-core = { path = "crates/lib/imap-tls-core" }

async-imap = { version = "0.11", default-features = false, features = ["runtime-tokio"] }
rustls = "0.23"
rustls-native-certs = "0.8"
tokio-rustls = "0.26"
color-eyre = "0.6"
thiserror = "1"
tokio = { version = "1", default-features = false }
tracing = "0.1"
tracing-subscriber = "0.3"
