[package]
name = "cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
color-eyre = { workspace = true }
config-bringup = { workspace = true }
config-load = { workspace = true }
imap-monitor = { workspace = true }
monitoring-engine = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
